-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity PSDMonitorTop_PSDMonitorTop_Pipeline_VITIS_LOOP_27_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    error_accum_load : IN STD_LOGIC_VECTOR (31 downto 0);
    max_samples : IN STD_LOGIC_VECTOR (31 downto 0);
    ram_buffer : IN STD_LOGIC_VECTOR (63 downto 0);
    adc_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    adc_in_TVALID : IN STD_LOGIC;
    adc_in_TREADY : OUT STD_LOGIC;
    adc_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    adc_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    adc_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    error_accum_flag_0_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    error_accum_flag_0_out_ap_vld : OUT STD_LOGIC;
    error_accum_loc_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    error_accum_loc_0_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of PSDMonitorTop_PSDMonitorTop_Pipeline_VITIS_LOOP_27_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv16_64 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001100100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln27_reg_378 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_reg_378_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_391 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_391_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op63_writereq_state3 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal icmp_ln27_reg_378_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_391_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op65_write_state4 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal icmp_ln27_reg_378_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_391_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op70_writeresp_state9 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln27_fu_219_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal counter : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal fake_counter : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal gmem_blk_n_AW : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem_blk_n_W : STD_LOGIC;
    signal gmem_blk_n_B : STD_LOGIC;
    signal error_accum_flag_0_reg_174 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln27_reg_378_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_reg_378_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_reg_378_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_reg_378_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_vld_reg_382 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_adc1_fu_233_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal val_adc1_reg_386 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln43_fu_241_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_391_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_391_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_391_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_391_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_addr_reg_395 : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_addr_reg_395_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal avg_error_reg_406 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_error_accum_flag_0_phi_fu_178_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_phi_mux_storemerge_phi_fu_190_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_phi_reg_pp0_iter0_storemerge_reg_187 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln54_fu_247_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_phi_reg_pp0_iter0_val_adc1_2_reg_197 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_val_adc1_2_reg_197 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter2_val_adc1_2_reg_197 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln47_fu_282_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal add_ln38_fu_313_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal error_accum_loc_0_fu_106 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_ln41_fu_332_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal mem_idx_fu_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal mem_idx_3_fu_292_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_mem_idx_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_nbread_fu_132_p5_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_254_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln47_fu_262_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln47_fu_266_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln_fu_272_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal sext_ln41_fu_328_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_279 : BOOLEAN;
    signal ap_condition_465 : BOOLEAN;
    signal ap_condition_469 : BOOLEAN;
    signal ap_condition_473 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component PSDMonitorTop_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component PSDMonitorTop_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_val_adc1_2_reg_197_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_279)) then
                if (((p_vld_reg_382 = ap_const_lv1_0) and (icmp_ln27_reg_378 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter2_val_adc1_2_reg_197 <= fake_counter;
                elsif (((p_vld_reg_382 = ap_const_lv1_1) and (icmp_ln27_reg_378 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter2_val_adc1_2_reg_197 <= val_adc1_reg_386;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_val_adc1_2_reg_197 <= ap_phi_reg_pp0_iter1_val_adc1_2_reg_197;
                end if;
            end if; 
        end if;
    end process;

    error_accum_flag_0_reg_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln27_reg_378_pp0_iter7_reg = ap_const_lv1_1))) then 
                error_accum_flag_0_reg_174 <= ap_const_lv1_1;
            elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                error_accum_flag_0_reg_174 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    error_accum_loc_0_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    error_accum_loc_0_fu_106 <= error_accum_load;
                elsif ((ap_const_boolean_1 = ap_condition_469)) then 
                    error_accum_loc_0_fu_106 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_465)) then 
                    error_accum_loc_0_fu_106 <= add_ln41_fu_332_p2;
                end if;
            end if; 
        end if;
    end process;

    mem_idx_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_const_boolean_1 = ap_condition_473)) then 
                    mem_idx_fu_110 <= mem_idx_3_fu_292_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    mem_idx_fu_110 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                gmem_addr_reg_395 <= sext_ln47_fu_282_p1;
                gmem_addr_reg_395_pp0_iter1_reg <= gmem_addr_reg_395;
                icmp_ln27_reg_378 <= icmp_ln27_fu_219_p2;
                icmp_ln27_reg_378_pp0_iter1_reg <= icmp_ln27_reg_378;
                icmp_ln43_reg_391 <= icmp_ln43_fu_241_p2;
                icmp_ln43_reg_391_pp0_iter1_reg <= icmp_ln43_reg_391;
                p_vld_reg_382 <= empty_nbread_fu_132_p5_0;
                val_adc1_reg_386 <= val_adc1_fu_233_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                avg_error_reg_406 <= add_ln41_fu_332_p2(25 downto 10);
                icmp_ln27_reg_378_pp0_iter2_reg <= icmp_ln27_reg_378_pp0_iter1_reg;
                icmp_ln27_reg_378_pp0_iter3_reg <= icmp_ln27_reg_378_pp0_iter2_reg;
                icmp_ln27_reg_378_pp0_iter4_reg <= icmp_ln27_reg_378_pp0_iter3_reg;
                icmp_ln27_reg_378_pp0_iter5_reg <= icmp_ln27_reg_378_pp0_iter4_reg;
                icmp_ln27_reg_378_pp0_iter6_reg <= icmp_ln27_reg_378_pp0_iter5_reg;
                icmp_ln27_reg_378_pp0_iter7_reg <= icmp_ln27_reg_378_pp0_iter6_reg;
                icmp_ln43_reg_391_pp0_iter2_reg <= icmp_ln43_reg_391_pp0_iter1_reg;
                icmp_ln43_reg_391_pp0_iter3_reg <= icmp_ln43_reg_391_pp0_iter2_reg;
                icmp_ln43_reg_391_pp0_iter4_reg <= icmp_ln43_reg_391_pp0_iter3_reg;
                icmp_ln43_reg_391_pp0_iter5_reg <= icmp_ln43_reg_391_pp0_iter4_reg;
                icmp_ln43_reg_391_pp0_iter6_reg <= icmp_ln43_reg_391_pp0_iter5_reg;
                icmp_ln43_reg_391_pp0_iter7_reg <= icmp_ln43_reg_391_pp0_iter6_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter1_val_adc1_2_reg_197 <= ap_phi_reg_pp0_iter0_val_adc1_2_reg_197;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln27_fu_219_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                counter <= ap_phi_mux_storemerge_phi_fu_190_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (p_vld_reg_382 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln27_reg_378 = ap_const_lv1_1))) then
                fake_counter <= add_ln38_fu_313_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    adc_in_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln27_fu_219_p2, adc_in_TVALID, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = adc_in_TVALID) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln27_fu_219_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            adc_in_TREADY <= ap_const_logic_1;
        else 
            adc_in_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    add_ln38_fu_313_p2 <= std_logic_vector(unsigned(fake_counter) + unsigned(ap_const_lv16_64));
    add_ln41_fu_332_p2 <= std_logic_vector(unsigned(error_accum_loc_0_fu_106) + unsigned(sext_ln41_fu_328_p1));
    add_ln47_fu_266_p2 <= std_logic_vector(unsigned(zext_ln47_fu_262_p1) + unsigned(ram_buffer));
    add_ln54_fu_247_p2 <= std_logic_vector(unsigned(counter) + unsigned(ap_const_lv11_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_state9_pp0_stage0_iter8)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter8));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter8, ap_block_state3_io, ap_block_state4_io, ap_block_state9_pp0_stage0_iter8)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter8)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter8, ap_block_state3_io, ap_block_state4_io, ap_block_state9_pp0_stage0_iter8)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter8)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io)));
    end process;


    ap_block_state3_io_assign_proc : process(m_axi_gmem_AWREADY, ap_predicate_op63_writereq_state3)
    begin
                ap_block_state3_io <= ((m_axi_gmem_AWREADY = ap_const_logic_0) and (ap_predicate_op63_writereq_state3 = ap_const_boolean_1));
    end process;


    ap_block_state4_io_assign_proc : process(m_axi_gmem_WREADY, ap_predicate_op65_write_state4)
    begin
                ap_block_state4_io <= ((m_axi_gmem_WREADY = ap_const_logic_0) and (ap_predicate_op65_write_state4 = ap_const_boolean_1));
    end process;


    ap_block_state9_pp0_stage0_iter8_assign_proc : process(m_axi_gmem_BVALID, ap_predicate_op70_writeresp_state9)
    begin
                ap_block_state9_pp0_stage0_iter8 <= ((m_axi_gmem_BVALID = ap_const_logic_0) and (ap_predicate_op70_writeresp_state9 = ap_const_boolean_1));
    end process;


    ap_condition_279_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_279 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_465_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln27_reg_378_pp0_iter1_reg, icmp_ln43_reg_391_pp0_iter1_reg)
    begin
                ap_condition_465 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_391_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln27_reg_378_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_condition_469_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln27_reg_378_pp0_iter1_reg, icmp_ln43_reg_391_pp0_iter1_reg)
    begin
                ap_condition_469 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_391_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln27_reg_378_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_condition_473_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln27_fu_219_p2, icmp_ln43_fu_241_p2)
    begin
                ap_condition_473 <= ((icmp_ln43_fu_241_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln27_fu_219_p2 = ap_const_lv1_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln27_fu_219_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln27_fu_219_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter7_reg, ap_done_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_error_accum_flag_0_phi_fu_178_p4_assign_proc : process(ap_enable_reg_pp0_iter8, icmp_ln27_reg_378_pp0_iter7_reg, ap_block_pp0_stage0, error_accum_flag_0_reg_174)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln27_reg_378_pp0_iter7_reg = ap_const_lv1_1))) then 
            ap_phi_mux_error_accum_flag_0_phi_fu_178_p4 <= ap_const_lv1_1;
        else 
            ap_phi_mux_error_accum_flag_0_phi_fu_178_p4 <= error_accum_flag_0_reg_174;
        end if; 
    end process;


    ap_phi_mux_storemerge_phi_fu_190_p4_assign_proc : process(icmp_ln27_fu_219_p2, icmp_ln43_fu_241_p2, ap_phi_reg_pp0_iter0_storemerge_reg_187, add_ln54_fu_247_p2)
    begin
        if ((icmp_ln27_fu_219_p2 = ap_const_lv1_1)) then
            if ((icmp_ln43_fu_241_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_storemerge_phi_fu_190_p4 <= add_ln54_fu_247_p2;
            elsif ((icmp_ln43_fu_241_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_storemerge_phi_fu_190_p4 <= ap_const_lv11_0;
            else 
                ap_phi_mux_storemerge_phi_fu_190_p4 <= ap_phi_reg_pp0_iter0_storemerge_reg_187;
            end if;
        else 
            ap_phi_mux_storemerge_phi_fu_190_p4 <= ap_phi_reg_pp0_iter0_storemerge_reg_187;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_storemerge_reg_187 <= "XXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_val_adc1_2_reg_197 <= "XXXXXXXXXXXXXXXX";

    ap_predicate_op63_writereq_state3_assign_proc : process(icmp_ln27_reg_378_pp0_iter1_reg, icmp_ln43_reg_391_pp0_iter1_reg)
    begin
                ap_predicate_op63_writereq_state3 <= ((icmp_ln43_reg_391_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln27_reg_378_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op65_write_state4_assign_proc : process(icmp_ln27_reg_378_pp0_iter2_reg, icmp_ln43_reg_391_pp0_iter2_reg)
    begin
                ap_predicate_op65_write_state4 <= ((icmp_ln43_reg_391_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln27_reg_378_pp0_iter2_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op70_writeresp_state9_assign_proc : process(icmp_ln27_reg_378_pp0_iter7_reg, icmp_ln43_reg_391_pp0_iter7_reg)
    begin
                ap_predicate_op70_writeresp_state9 <= ((icmp_ln43_reg_391_pp0_iter7_reg = ap_const_lv1_1) and (icmp_ln27_reg_378_pp0_iter7_reg = ap_const_lv1_1));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_mem_idx_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, mem_idx_fu_110)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_mem_idx_2 <= ap_const_lv32_0;
        else 
            ap_sig_allocacmp_mem_idx_2 <= mem_idx_fu_110;
        end if; 
    end process;

    empty_nbread_fu_132_p5_0 <= (0=>(adc_in_TVALID), others=>'-');
    error_accum_flag_0_out <= ap_phi_mux_error_accum_flag_0_phi_fu_178_p4;

    error_accum_flag_0_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln27_reg_378_pp0_iter6_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (icmp_ln27_reg_378_pp0_iter6_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            error_accum_flag_0_out_ap_vld <= ap_const_logic_1;
        else 
            error_accum_flag_0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    error_accum_loc_0_out <= error_accum_loc_0_fu_106;

    error_accum_loc_0_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln27_reg_378_pp0_iter6_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (icmp_ln27_reg_378_pp0_iter6_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            error_accum_loc_0_out_ap_vld <= ap_const_logic_1;
        else 
            error_accum_loc_0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    gmem_blk_n_AW_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_AWREADY, ap_predicate_op63_writereq_state3, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op63_writereq_state3 = ap_const_boolean_1))) then 
            gmem_blk_n_AW <= m_axi_gmem_AWREADY;
        else 
            gmem_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter8, m_axi_gmem_BVALID, ap_predicate_op70_writeresp_state9, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op70_writeresp_state9 = ap_const_boolean_1))) then 
            gmem_blk_n_B <= m_axi_gmem_BVALID;
        else 
            gmem_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem_WREADY, ap_predicate_op65_write_state4, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op65_write_state4 = ap_const_boolean_1))) then 
            gmem_blk_n_W <= m_axi_gmem_WREADY;
        else 
            gmem_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln27_fu_219_p2 <= "1" when (unsigned(ap_sig_allocacmp_mem_idx_2) < unsigned(max_samples)) else "0";
    icmp_ln43_fu_241_p2 <= "1" when (counter = ap_const_lv11_3FF) else "0";
    m_axi_gmem_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_ARID <= ap_const_lv1_0;
    m_axi_gmem_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_ARVALID <= ap_const_logic_0;
    m_axi_gmem_AWADDR <= gmem_addr_reg_395_pp0_iter1_reg;
    m_axi_gmem_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_AWID <= ap_const_lv1_0;
    m_axi_gmem_AWLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_gmem_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_AWUSER <= ap_const_lv1_0;

    m_axi_gmem_AWVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op63_writereq_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op63_writereq_state3 = ap_const_boolean_1))) then 
            m_axi_gmem_AWVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem_BREADY_assign_proc : process(ap_enable_reg_pp0_iter8, ap_predicate_op70_writeresp_state9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op70_writeresp_state9 = ap_const_boolean_1))) then 
            m_axi_gmem_BREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_RREADY <= ap_const_logic_0;
    m_axi_gmem_WDATA <= avg_error_reg_406;
    m_axi_gmem_WID <= ap_const_lv1_0;
    m_axi_gmem_WLAST <= ap_const_logic_0;
    m_axi_gmem_WSTRB <= ap_const_lv2_3;
    m_axi_gmem_WUSER <= ap_const_lv1_0;

    m_axi_gmem_WVALID_assign_proc : process(ap_enable_reg_pp0_iter3, ap_predicate_op65_write_state4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op65_write_state4 = ap_const_boolean_1))) then 
            m_axi_gmem_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    mem_idx_3_fu_292_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_mem_idx_2) + unsigned(ap_const_lv32_1));
        sext_ln41_fu_328_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_phi_reg_pp0_iter2_val_adc1_2_reg_197),32));

        sext_ln47_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_272_p4),64));

    shl_ln_fu_254_p3 <= (ap_sig_allocacmp_mem_idx_2 & ap_const_lv1_0);
    trunc_ln_fu_272_p4 <= add_ln47_fu_266_p2(63 downto 1);
    val_adc1_fu_233_p1 <= adc_in_TDATA(16 - 1 downto 0);
    zext_ln47_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_254_p3),64));
end behav;
