-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity PSDMonitorTop is
generic (
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0);
    adc_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    adc_in_TVALID : IN STD_LOGIC;
    adc_in_TREADY : OUT STD_LOGIC;
    adc_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    adc_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    adc_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of PSDMonitorTop is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "PSDMonitorTop_PSDMonitorTop,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.840000,HLS_SYN_LAT=7,HLS_SYN_TPT=1,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=1194,HLS_SYN_LUT=1409,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_3FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001111111111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ram_buffer : STD_LOGIC_VECTOR (63 downto 0);
    signal max_samples : STD_LOGIC_VECTOR (31 downto 0);
    signal en_logging : STD_LOGIC_VECTOR (0 downto 0);
    signal error_accum : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal mem_idx : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal counter : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal gmem_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal en_logging_read_reg_315 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_reg_319 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_328 : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_blk_n_W : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal en_logging_read_reg_315_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_reg_319_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_328_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_blk_n_B : STD_LOGIC;
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal en_logging_read_reg_315_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_reg_319_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_328_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal adc_in_TDATA_blk_n : STD_LOGIC;
    signal en_logging_read_read_fu_114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal gmem_AWVALID : STD_LOGIC;
    signal gmem_AWREADY : STD_LOGIC;
    signal gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_WVALID : STD_LOGIC;
    signal gmem_WREADY : STD_LOGIC;
    signal gmem_ARREADY : STD_LOGIC;
    signal gmem_RVALID : STD_LOGIC;
    signal gmem_RDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal gmem_RFIFONUM : STD_LOGIC_VECTOR (9 downto 0);
    signal gmem_BVALID : STD_LOGIC;
    signal gmem_BREADY : STD_LOGIC;
    signal ap_predicate_op62_writereq_state2 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_predicate_op63_write_state3 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_predicate_op68_writeresp_state8 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal en_logging_read_reg_315_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal en_logging_read_reg_315_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal en_logging_read_reg_315_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal en_logging_read_reg_315_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_fu_219_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_reg_319_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_reg_319_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_reg_319_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_reg_319_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal avg_error_reg_323 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_328_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_328_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_328_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_328_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_addr_reg_332 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln36_fu_308_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln36_reg_338 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_phi_mux_error_accum_new_0_phi_fu_163_p6 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_phi_reg_pp0_iter0_error_accum_new_0_reg_160 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln33_fu_208_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_phi_mux_storemerge1_phi_fu_176_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_storemerge1_reg_173 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln46_fu_225_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln39_fu_274_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal add_ln40_fu_284_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln33_fu_204_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln_fu_246_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln39_fu_254_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln39_fu_258_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln1_fu_264_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_adc_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal adc_in_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal adc_in_TVALID_int_regslice : STD_LOGIC;
    signal adc_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_adc_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_adc_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal adc_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_adc_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_adc_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_adc_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal adc_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_adc_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_adc_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_adc_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal adc_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_adc_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_adc_in_V_last_V_U_ack_in : STD_LOGIC;
    signal ap_condition_342 : BOOLEAN;
    signal ap_condition_323 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component PSDMonitorTop_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ram_buffer : OUT STD_LOGIC_VECTOR (63 downto 0);
        max_samples : OUT STD_LOGIC_VECTOR (31 downto 0);
        en_logging : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component PSDMonitorTop_gmem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (9 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;


    component PSDMonitorTop_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    CTRL_s_axi_U : component PSDMonitorTop_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ram_buffer => ram_buffer,
        max_samples => max_samples,
        en_logging => en_logging);

    gmem_m_axi_U : component PSDMonitorTop_gmem_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 4,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 10,
        CH0_USER_DW => 16,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 0,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_gmem_AWVALID,
        AWREADY => m_axi_gmem_AWREADY,
        AWADDR => m_axi_gmem_AWADDR,
        AWID => m_axi_gmem_AWID,
        AWLEN => m_axi_gmem_AWLEN,
        AWSIZE => m_axi_gmem_AWSIZE,
        AWBURST => m_axi_gmem_AWBURST,
        AWLOCK => m_axi_gmem_AWLOCK,
        AWCACHE => m_axi_gmem_AWCACHE,
        AWPROT => m_axi_gmem_AWPROT,
        AWQOS => m_axi_gmem_AWQOS,
        AWREGION => m_axi_gmem_AWREGION,
        AWUSER => m_axi_gmem_AWUSER,
        WVALID => m_axi_gmem_WVALID,
        WREADY => m_axi_gmem_WREADY,
        WDATA => m_axi_gmem_WDATA,
        WSTRB => m_axi_gmem_WSTRB,
        WLAST => m_axi_gmem_WLAST,
        WID => m_axi_gmem_WID,
        WUSER => m_axi_gmem_WUSER,
        ARVALID => m_axi_gmem_ARVALID,
        ARREADY => m_axi_gmem_ARREADY,
        ARADDR => m_axi_gmem_ARADDR,
        ARID => m_axi_gmem_ARID,
        ARLEN => m_axi_gmem_ARLEN,
        ARSIZE => m_axi_gmem_ARSIZE,
        ARBURST => m_axi_gmem_ARBURST,
        ARLOCK => m_axi_gmem_ARLOCK,
        ARCACHE => m_axi_gmem_ARCACHE,
        ARPROT => m_axi_gmem_ARPROT,
        ARQOS => m_axi_gmem_ARQOS,
        ARREGION => m_axi_gmem_ARREGION,
        ARUSER => m_axi_gmem_ARUSER,
        RVALID => m_axi_gmem_RVALID,
        RREADY => m_axi_gmem_RREADY,
        RDATA => m_axi_gmem_RDATA,
        RLAST => m_axi_gmem_RLAST,
        RID => m_axi_gmem_RID,
        RUSER => m_axi_gmem_RUSER,
        RRESP => m_axi_gmem_RRESP,
        BVALID => m_axi_gmem_BVALID,
        BREADY => m_axi_gmem_BREADY,
        BRESP => m_axi_gmem_BRESP,
        BID => m_axi_gmem_BID,
        BUSER => m_axi_gmem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => ap_const_logic_0,
        I_CH0_ARREADY => gmem_ARREADY,
        I_CH0_ARADDR => ap_const_lv64_0,
        I_CH0_ARLEN => ap_const_lv32_0,
        I_CH0_RVALID => gmem_RVALID,
        I_CH0_RREADY => ap_const_logic_0,
        I_CH0_RDATA => gmem_RDATA,
        I_CH0_RFIFONUM => gmem_RFIFONUM,
        I_CH0_AWVALID => gmem_AWVALID,
        I_CH0_AWREADY => gmem_AWREADY,
        I_CH0_AWADDR => gmem_addr_reg_332,
        I_CH0_AWLEN => gmem_AWLEN,
        I_CH0_WVALID => gmem_WVALID,
        I_CH0_WREADY => gmem_WREADY,
        I_CH0_WDATA => select_ln36_reg_338,
        I_CH0_WSTRB => ap_const_lv2_3,
        I_CH0_BVALID => gmem_BVALID,
        I_CH0_BREADY => gmem_BREADY);

    regslice_both_adc_in_V_data_V_U : component PSDMonitorTop_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => adc_in_TDATA,
        vld_in => adc_in_TVALID,
        ack_in => regslice_both_adc_in_V_data_V_U_ack_in,
        data_out => adc_in_TDATA_int_regslice,
        vld_out => adc_in_TVALID_int_regslice,
        ack_out => adc_in_TREADY_int_regslice,
        apdone_blk => regslice_both_adc_in_V_data_V_U_apdone_blk);

    regslice_both_adc_in_V_keep_V_U : component PSDMonitorTop_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => adc_in_TKEEP,
        vld_in => adc_in_TVALID,
        ack_in => regslice_both_adc_in_V_keep_V_U_ack_in,
        data_out => adc_in_TKEEP_int_regslice,
        vld_out => regslice_both_adc_in_V_keep_V_U_vld_out,
        ack_out => adc_in_TREADY_int_regslice,
        apdone_blk => regslice_both_adc_in_V_keep_V_U_apdone_blk);

    regslice_both_adc_in_V_strb_V_U : component PSDMonitorTop_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => adc_in_TSTRB,
        vld_in => adc_in_TVALID,
        ack_in => regslice_both_adc_in_V_strb_V_U_ack_in,
        data_out => adc_in_TSTRB_int_regslice,
        vld_out => regslice_both_adc_in_V_strb_V_U_vld_out,
        ack_out => adc_in_TREADY_int_regslice,
        apdone_blk => regslice_both_adc_in_V_strb_V_U_apdone_blk);

    regslice_both_adc_in_V_last_V_U : component PSDMonitorTop_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => adc_in_TLAST,
        vld_in => adc_in_TVALID,
        ack_in => regslice_both_adc_in_V_last_V_U_ack_in,
        data_out => adc_in_TLAST_int_regslice,
        vld_out => regslice_both_adc_in_V_last_V_U_vld_out,
        ack_out => adc_in_TREADY_int_regslice,
        apdone_blk => regslice_both_adc_in_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    mem_idx_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_323)) then
                if ((ap_const_boolean_1 = ap_condition_342)) then 
                    mem_idx <= add_ln40_fu_284_p2;
                elsif ((en_logging_read_read_fu_114_p2 = ap_const_lv1_0)) then 
                    mem_idx <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                avg_error_reg_323 <= add_ln33_fu_208_p2(10 downto 10);
                en_logging_read_reg_315 <= en_logging;
                en_logging_read_reg_315_pp0_iter1_reg <= en_logging_read_reg_315;
                gmem_addr_reg_332 <= sext_ln39_fu_274_p1;
                icmp_ln35_reg_319 <= icmp_ln35_fu_219_p2;
                icmp_ln35_reg_319_pp0_iter1_reg <= icmp_ln35_reg_319;
                icmp_ln38_reg_328 <= icmp_ln38_fu_240_p2;
                icmp_ln38_reg_328_pp0_iter1_reg <= icmp_ln38_reg_328;
                select_ln36_reg_338 <= select_ln36_fu_308_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1))) then
                counter <= ap_phi_mux_storemerge1_phi_fu_176_p6;
                error_accum <= ap_phi_mux_error_accum_new_0_phi_fu_163_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                en_logging_read_reg_315_pp0_iter2_reg <= en_logging_read_reg_315_pp0_iter1_reg;
                en_logging_read_reg_315_pp0_iter3_reg <= en_logging_read_reg_315_pp0_iter2_reg;
                en_logging_read_reg_315_pp0_iter4_reg <= en_logging_read_reg_315_pp0_iter3_reg;
                en_logging_read_reg_315_pp0_iter5_reg <= en_logging_read_reg_315_pp0_iter4_reg;
                en_logging_read_reg_315_pp0_iter6_reg <= en_logging_read_reg_315_pp0_iter5_reg;
                icmp_ln35_reg_319_pp0_iter2_reg <= icmp_ln35_reg_319_pp0_iter1_reg;
                icmp_ln35_reg_319_pp0_iter3_reg <= icmp_ln35_reg_319_pp0_iter2_reg;
                icmp_ln35_reg_319_pp0_iter4_reg <= icmp_ln35_reg_319_pp0_iter3_reg;
                icmp_ln35_reg_319_pp0_iter5_reg <= icmp_ln35_reg_319_pp0_iter4_reg;
                icmp_ln35_reg_319_pp0_iter6_reg <= icmp_ln35_reg_319_pp0_iter5_reg;
                icmp_ln38_reg_328_pp0_iter2_reg <= icmp_ln38_reg_328_pp0_iter1_reg;
                icmp_ln38_reg_328_pp0_iter3_reg <= icmp_ln38_reg_328_pp0_iter2_reg;
                icmp_ln38_reg_328_pp0_iter4_reg <= icmp_ln38_reg_328_pp0_iter3_reg;
                icmp_ln38_reg_328_pp0_iter5_reg <= icmp_ln38_reg_328_pp0_iter4_reg;
                icmp_ln38_reg_328_pp0_iter6_reg <= icmp_ln38_reg_328_pp0_iter5_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    adc_in_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, adc_in_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1))) then 
            adc_in_TDATA_blk_n <= adc_in_TVALID_int_regslice;
        else 
            adc_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    adc_in_TREADY <= regslice_both_adc_in_V_data_V_U_ack_in;

    adc_in_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1))) then 
            adc_in_TREADY_int_regslice <= ap_const_logic_1;
        else 
            adc_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    add_ln33_fu_208_p2 <= std_logic_vector(unsigned(error_accum) + unsigned(trunc_ln33_fu_204_p1));
    add_ln39_fu_258_p2 <= std_logic_vector(unsigned(zext_ln39_fu_254_p1) + unsigned(ram_buffer));
    add_ln40_fu_284_p2 <= std_logic_vector(unsigned(mem_idx) + unsigned(ap_const_lv32_1));
    add_ln46_fu_225_p2 <= std_logic_vector(unsigned(counter) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_state1_pp0_stage0_iter0, ap_block_state8_pp0_stage0_iter7)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter7) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter7, ap_block_state1_pp0_stage0_iter0, ap_block_state2_io, ap_block_state3_io, ap_block_state8_pp0_stage0_iter7)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io)) or ((ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter7) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter7, ap_block_state1_pp0_stage0_iter0, ap_block_state2_io, ap_block_state3_io, ap_block_state8_pp0_stage0_iter7)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io)) or ((ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter7) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(adc_in_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_const_logic_0 = adc_in_TVALID_int_regslice);
    end process;


    ap_block_state2_io_assign_proc : process(gmem_AWREADY, ap_predicate_op62_writereq_state2)
    begin
                ap_block_state2_io <= ((ap_predicate_op62_writereq_state2 = ap_const_boolean_1) and (gmem_AWREADY = ap_const_logic_0));
    end process;


    ap_block_state3_io_assign_proc : process(gmem_WREADY, ap_predicate_op63_write_state3)
    begin
                ap_block_state3_io <= ((ap_predicate_op63_write_state3 = ap_const_boolean_1) and (gmem_WREADY = ap_const_logic_0));
    end process;


    ap_block_state8_pp0_stage0_iter7_assign_proc : process(gmem_BVALID, ap_predicate_op68_writeresp_state8)
    begin
                ap_block_state8_pp0_stage0_iter7 <= ((ap_predicate_op68_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0));
    end process;


    ap_condition_323_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_323 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1));
    end process;


    ap_condition_342_assign_proc : process(en_logging_read_read_fu_114_p2, icmp_ln35_fu_219_p2, icmp_ln38_fu_240_p2)
    begin
                ap_condition_342 <= ((icmp_ln38_fu_240_p2 = ap_const_lv1_1) and (icmp_ln35_fu_219_p2 = ap_const_lv1_1) and (en_logging_read_read_fu_114_p2 = ap_const_lv1_1));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_error_accum_new_0_phi_fu_163_p6_assign_proc : process(en_logging_read_read_fu_114_p2, icmp_ln35_fu_219_p2, ap_phi_reg_pp0_iter0_error_accum_new_0_reg_160, add_ln33_fu_208_p2)
    begin
        if (((icmp_ln35_fu_219_p2 = ap_const_lv1_0) and (en_logging_read_read_fu_114_p2 = ap_const_lv1_1))) then 
            ap_phi_mux_error_accum_new_0_phi_fu_163_p6 <= add_ln33_fu_208_p2;
        elsif (((en_logging_read_read_fu_114_p2 = ap_const_lv1_0) or ((icmp_ln35_fu_219_p2 = ap_const_lv1_1) and (en_logging_read_read_fu_114_p2 = ap_const_lv1_1)))) then 
            ap_phi_mux_error_accum_new_0_phi_fu_163_p6 <= ap_const_lv11_0;
        else 
            ap_phi_mux_error_accum_new_0_phi_fu_163_p6 <= ap_phi_reg_pp0_iter0_error_accum_new_0_reg_160;
        end if; 
    end process;


    ap_phi_mux_storemerge1_phi_fu_176_p6_assign_proc : process(en_logging_read_read_fu_114_p2, icmp_ln35_fu_219_p2, ap_phi_reg_pp0_iter0_storemerge1_reg_173, add_ln46_fu_225_p2)
    begin
        if (((icmp_ln35_fu_219_p2 = ap_const_lv1_0) and (en_logging_read_read_fu_114_p2 = ap_const_lv1_1))) then 
            ap_phi_mux_storemerge1_phi_fu_176_p6 <= add_ln46_fu_225_p2;
        elsif (((en_logging_read_read_fu_114_p2 = ap_const_lv1_0) or ((icmp_ln35_fu_219_p2 = ap_const_lv1_1) and (en_logging_read_read_fu_114_p2 = ap_const_lv1_1)))) then 
            ap_phi_mux_storemerge1_phi_fu_176_p6 <= ap_const_lv32_0;
        else 
            ap_phi_mux_storemerge1_phi_fu_176_p6 <= ap_phi_reg_pp0_iter0_storemerge1_reg_173;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_error_accum_new_0_reg_160 <= "XXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_storemerge1_reg_173 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op62_writereq_state2_assign_proc : process(en_logging_read_reg_315, icmp_ln35_reg_319, icmp_ln38_reg_328)
    begin
                ap_predicate_op62_writereq_state2 <= ((icmp_ln38_reg_328 = ap_const_lv1_1) and (icmp_ln35_reg_319 = ap_const_lv1_1) and (en_logging_read_reg_315 = ap_const_lv1_1));
    end process;


    ap_predicate_op63_write_state3_assign_proc : process(en_logging_read_reg_315_pp0_iter1_reg, icmp_ln35_reg_319_pp0_iter1_reg, icmp_ln38_reg_328_pp0_iter1_reg)
    begin
                ap_predicate_op63_write_state3 <= ((icmp_ln38_reg_328_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln35_reg_319_pp0_iter1_reg = ap_const_lv1_1) and (en_logging_read_reg_315_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op68_writeresp_state8_assign_proc : process(en_logging_read_reg_315_pp0_iter6_reg, icmp_ln35_reg_319_pp0_iter6_reg, icmp_ln38_reg_328_pp0_iter6_reg)
    begin
                ap_predicate_op68_writeresp_state8 <= ((icmp_ln38_reg_328_pp0_iter6_reg = ap_const_lv1_1) and (icmp_ln35_reg_319_pp0_iter6_reg = ap_const_lv1_1) and (en_logging_read_reg_315_pp0_iter6_reg = ap_const_lv1_1));
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    en_logging_read_read_fu_114_p2 <= en_logging;
    gmem_AWLEN <= ap_const_lv64_1(32 - 1 downto 0);

    gmem_AWVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op62_writereq_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op62_writereq_state2 = ap_const_boolean_1))) then 
            gmem_AWVALID <= ap_const_logic_1;
        else 
            gmem_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_BREADY_assign_proc : process(ap_enable_reg_pp0_iter7, ap_predicate_op68_writeresp_state8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op68_writeresp_state8 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            gmem_BREADY <= ap_const_logic_1;
        else 
            gmem_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_WVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op63_write_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op63_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            gmem_WVALID <= ap_const_logic_1;
        else 
            gmem_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_blk_n_AW_assign_proc : process(m_axi_gmem_AWREADY, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, en_logging_read_reg_315, icmp_ln35_reg_319, icmp_ln38_reg_328)
    begin
        if (((icmp_ln38_reg_328 = ap_const_lv1_1) and (icmp_ln35_reg_319 = ap_const_lv1_1) and (en_logging_read_reg_315 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem_blk_n_AW <= m_axi_gmem_AWREADY;
        else 
            gmem_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_B_assign_proc : process(m_axi_gmem_BVALID, ap_block_pp0_stage0, ap_enable_reg_pp0_iter7, en_logging_read_reg_315_pp0_iter6_reg, icmp_ln35_reg_319_pp0_iter6_reg, icmp_ln38_reg_328_pp0_iter6_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln38_reg_328_pp0_iter6_reg = ap_const_lv1_1) and (icmp_ln35_reg_319_pp0_iter6_reg = ap_const_lv1_1) and (en_logging_read_reg_315_pp0_iter6_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            gmem_blk_n_B <= m_axi_gmem_BVALID;
        else 
            gmem_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_W_assign_proc : process(m_axi_gmem_WREADY, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, en_logging_read_reg_315_pp0_iter1_reg, icmp_ln35_reg_319_pp0_iter1_reg, icmp_ln38_reg_328_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln38_reg_328_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln35_reg_319_pp0_iter1_reg = ap_const_lv1_1) and (en_logging_read_reg_315_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            gmem_blk_n_W <= m_axi_gmem_WREADY;
        else 
            gmem_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln35_fu_219_p2 <= "1" when (counter = ap_const_lv32_3FF) else "0";
    icmp_ln38_fu_240_p2 <= "1" when (unsigned(mem_idx) < unsigned(max_samples)) else "0";
    select_ln36_fu_308_p3 <= 
        ap_const_lv16_FFFF when (avg_error_reg_323(0) = '1') else 
        ap_const_lv16_0;
        sext_ln39_fu_274_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_fu_264_p4),64));

    shl_ln_fu_246_p3 <= (mem_idx & ap_const_lv1_0);
    trunc_ln1_fu_264_p4 <= add_ln39_fu_258_p2(63 downto 1);
    trunc_ln33_fu_204_p1 <= adc_in_TDATA_int_regslice(11 - 1 downto 0);
    zext_ln39_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_246_p3),64));
end behav;
