// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module PSDMonitorTop_PSDMonitorTop_Pipeline_VITIS_LOOP_27_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        error_accum_load,
        max_samples,
        ram_buffer,
        adc_in_TDATA,
        adc_in_TVALID,
        adc_in_TREADY,
        adc_in_TKEEP,
        adc_in_TSTRB,
        adc_in_TLAST,
        error_accum_flag_0_out,
        error_accum_flag_0_out_ap_vld,
        error_accum_loc_0_out,
        error_accum_loc_0_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [15:0] m_axi_gmem_WDATA;
output  [1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [15:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [9:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [31:0] error_accum_load;
input  [31:0] max_samples;
input  [63:0] ram_buffer;
input  [31:0] adc_in_TDATA;
input   adc_in_TVALID;
output   adc_in_TREADY;
input  [3:0] adc_in_TKEEP;
input  [3:0] adc_in_TSTRB;
input  [0:0] adc_in_TLAST;
output  [0:0] error_accum_flag_0_out;
output   error_accum_flag_0_out_ap_vld;
output  [31:0] error_accum_loc_0_out;
output   error_accum_loc_0_out_ap_vld;

reg ap_idle;
reg m_axi_gmem_AWVALID;
reg m_axi_gmem_WVALID;
reg m_axi_gmem_BREADY;
reg adc_in_TREADY;
reg error_accum_flag_0_out_ap_vld;
reg error_accum_loc_0_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln27_reg_378;
reg   [0:0] icmp_ln27_reg_378_pp0_iter1_reg;
reg   [0:0] icmp_ln43_reg_391;
reg   [0:0] icmp_ln43_reg_391_pp0_iter1_reg;
reg    ap_predicate_op63_writereq_state3;
reg    ap_block_state3_io;
reg   [0:0] icmp_ln27_reg_378_pp0_iter2_reg;
reg   [0:0] icmp_ln43_reg_391_pp0_iter2_reg;
reg    ap_predicate_op65_write_state4;
reg    ap_block_state4_io;
reg   [0:0] icmp_ln27_reg_378_pp0_iter7_reg;
reg   [0:0] icmp_ln43_reg_391_pp0_iter7_reg;
reg    ap_predicate_op70_writeresp_state9;
reg    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln27_fu_219_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [10:0] counter;
reg   [15:0] fake_counter;
reg    gmem_blk_n_AW;
wire    ap_block_pp0_stage0;
reg    gmem_blk_n_W;
reg    gmem_blk_n_B;
reg   [0:0] error_accum_flag_0_reg_174;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln27_reg_378_pp0_iter3_reg;
reg   [0:0] icmp_ln27_reg_378_pp0_iter4_reg;
reg   [0:0] icmp_ln27_reg_378_pp0_iter5_reg;
reg   [0:0] icmp_ln27_reg_378_pp0_iter6_reg;
reg   [0:0] p_vld_reg_382;
wire   [15:0] val_adc1_fu_233_p1;
reg   [15:0] val_adc1_reg_386;
wire   [0:0] icmp_ln43_fu_241_p2;
reg   [0:0] icmp_ln43_reg_391_pp0_iter3_reg;
reg   [0:0] icmp_ln43_reg_391_pp0_iter4_reg;
reg   [0:0] icmp_ln43_reg_391_pp0_iter5_reg;
reg   [0:0] icmp_ln43_reg_391_pp0_iter6_reg;
reg   [63:0] gmem_addr_reg_395;
reg   [63:0] gmem_addr_reg_395_pp0_iter1_reg;
reg   [15:0] avg_error_reg_406;
reg   [0:0] ap_phi_mux_error_accum_flag_0_phi_fu_178_p4;
wire    ap_loop_init;
reg   [10:0] ap_phi_mux_storemerge_phi_fu_190_p4;
wire   [10:0] ap_phi_reg_pp0_iter0_storemerge_reg_187;
wire   [10:0] add_ln54_fu_247_p2;
wire   [15:0] ap_phi_reg_pp0_iter0_val_adc1_2_reg_197;
reg   [15:0] ap_phi_reg_pp0_iter1_val_adc1_2_reg_197;
reg   [15:0] ap_phi_reg_pp0_iter2_val_adc1_2_reg_197;
wire  signed [63:0] sext_ln47_fu_282_p1;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] add_ln38_fu_313_p2;
reg   [31:0] error_accum_loc_0_fu_106;
wire   [31:0] add_ln41_fu_332_p2;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [31:0] mem_idx_fu_110;
wire   [31:0] mem_idx_3_fu_292_p2;
reg   [31:0] ap_sig_allocacmp_mem_idx_2;
wire   [0:0] empty_nbread_fu_132_p5_0;
wire   [32:0] shl_ln_fu_254_p3;
wire   [63:0] zext_ln47_fu_262_p1;
wire   [63:0] add_ln47_fu_266_p2;
wire   [62:0] trunc_ln_fu_272_p4;
wire  signed [31:0] sext_ln41_fu_328_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_279;
reg    ap_condition_465;
reg    ap_condition_469;
reg    ap_condition_473;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 counter = 11'd0;
#0 fake_counter = 16'd0;
#0 error_accum_loc_0_fu_106 = 32'd0;
#0 mem_idx_fu_110 = 32'd0;
#0 ap_done_reg = 1'b0;
end

PSDMonitorTop_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_279)) begin
        if (((p_vld_reg_382 == 1'd0) & (icmp_ln27_reg_378 == 1'd1))) begin
            ap_phi_reg_pp0_iter2_val_adc1_2_reg_197 <= fake_counter;
        end else if (((p_vld_reg_382 == 1'd1) & (icmp_ln27_reg_378 == 1'd1))) begin
            ap_phi_reg_pp0_iter2_val_adc1_2_reg_197 <= val_adc1_reg_386;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_val_adc1_2_reg_197 <= ap_phi_reg_pp0_iter1_val_adc1_2_reg_197;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln27_reg_378_pp0_iter7_reg == 1'd1))) begin
        error_accum_flag_0_reg_174 <= 1'd1;
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        error_accum_flag_0_reg_174 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            error_accum_loc_0_fu_106 <= error_accum_load;
        end else if ((1'b1 == ap_condition_469)) begin
            error_accum_loc_0_fu_106 <= 32'd0;
        end else if ((1'b1 == ap_condition_465)) begin
            error_accum_loc_0_fu_106 <= add_ln41_fu_332_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_473)) begin
            mem_idx_fu_110 <= mem_idx_3_fu_292_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            mem_idx_fu_110 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        gmem_addr_reg_395 <= sext_ln47_fu_282_p1;
        gmem_addr_reg_395_pp0_iter1_reg <= gmem_addr_reg_395;
        icmp_ln27_reg_378 <= icmp_ln27_fu_219_p2;
        icmp_ln27_reg_378_pp0_iter1_reg <= icmp_ln27_reg_378;
        icmp_ln43_reg_391 <= icmp_ln43_fu_241_p2;
        icmp_ln43_reg_391_pp0_iter1_reg <= icmp_ln43_reg_391;
        p_vld_reg_382 <= empty_nbread_fu_132_p5_0;
        val_adc1_reg_386 <= val_adc1_fu_233_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        avg_error_reg_406 <= {{add_ln41_fu_332_p2[25:10]}};
        icmp_ln27_reg_378_pp0_iter2_reg <= icmp_ln27_reg_378_pp0_iter1_reg;
        icmp_ln27_reg_378_pp0_iter3_reg <= icmp_ln27_reg_378_pp0_iter2_reg;
        icmp_ln27_reg_378_pp0_iter4_reg <= icmp_ln27_reg_378_pp0_iter3_reg;
        icmp_ln27_reg_378_pp0_iter5_reg <= icmp_ln27_reg_378_pp0_iter4_reg;
        icmp_ln27_reg_378_pp0_iter6_reg <= icmp_ln27_reg_378_pp0_iter5_reg;
        icmp_ln27_reg_378_pp0_iter7_reg <= icmp_ln27_reg_378_pp0_iter6_reg;
        icmp_ln43_reg_391_pp0_iter2_reg <= icmp_ln43_reg_391_pp0_iter1_reg;
        icmp_ln43_reg_391_pp0_iter3_reg <= icmp_ln43_reg_391_pp0_iter2_reg;
        icmp_ln43_reg_391_pp0_iter4_reg <= icmp_ln43_reg_391_pp0_iter3_reg;
        icmp_ln43_reg_391_pp0_iter5_reg <= icmp_ln43_reg_391_pp0_iter4_reg;
        icmp_ln43_reg_391_pp0_iter6_reg <= icmp_ln43_reg_391_pp0_iter5_reg;
        icmp_ln43_reg_391_pp0_iter7_reg <= icmp_ln43_reg_391_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_val_adc1_2_reg_197 <= ap_phi_reg_pp0_iter0_val_adc1_2_reg_197;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln27_fu_219_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        counter <= ap_phi_mux_storemerge_phi_fu_190_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (p_vld_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln27_reg_378 == 1'd1))) begin
        fake_counter <= add_ln38_fu_313_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == adc_in_TVALID) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln27_fu_219_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        adc_in_TREADY = 1'b1;
    end else begin
        adc_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln27_fu_219_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln27_reg_378_pp0_iter7_reg == 1'd1))) begin
        ap_phi_mux_error_accum_flag_0_phi_fu_178_p4 = 1'd1;
    end else begin
        ap_phi_mux_error_accum_flag_0_phi_fu_178_p4 = error_accum_flag_0_reg_174;
    end
end

always @ (*) begin
    if ((icmp_ln27_fu_219_p2 == 1'd1)) begin
        if ((icmp_ln43_fu_241_p2 == 1'd0)) begin
            ap_phi_mux_storemerge_phi_fu_190_p4 = add_ln54_fu_247_p2;
        end else if ((icmp_ln43_fu_241_p2 == 1'd1)) begin
            ap_phi_mux_storemerge_phi_fu_190_p4 = 11'd0;
        end else begin
            ap_phi_mux_storemerge_phi_fu_190_p4 = ap_phi_reg_pp0_iter0_storemerge_reg_187;
        end
    end else begin
        ap_phi_mux_storemerge_phi_fu_190_p4 = ap_phi_reg_pp0_iter0_storemerge_reg_187;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_mem_idx_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_mem_idx_2 = mem_idx_fu_110;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (icmp_ln27_reg_378_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        error_accum_flag_0_out_ap_vld = 1'b1;
    end else begin
        error_accum_flag_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (icmp_ln27_reg_378_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        error_accum_loc_0_out_ap_vld = 1'b1;
    end else begin
        error_accum_loc_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op63_writereq_state3 == 1'b1))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op70_writeresp_state9 == 1'b1))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op65_write_state4 == 1'b1))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op63_writereq_state3 == 1'b1))) begin
        m_axi_gmem_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op70_writeresp_state9 == 1'b1))) begin
        m_axi_gmem_BREADY = 1'b1;
    end else begin
        m_axi_gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op65_write_state4 == 1'b1))) begin
        m_axi_gmem_WVALID = 1'b1;
    end else begin
        m_axi_gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln38_fu_313_p2 = (fake_counter + 16'd100);

assign add_ln41_fu_332_p2 = ($signed(error_accum_loc_0_fu_106) + $signed(sext_ln41_fu_328_p1));

assign add_ln47_fu_266_p2 = (zext_ln47_fu_262_p1 + ram_buffer);

assign add_ln54_fu_247_p2 = (counter + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_state3_io = ((m_axi_gmem_AWREADY == 1'b0) & (ap_predicate_op63_writereq_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state4_io = ((m_axi_gmem_WREADY == 1'b0) & (ap_predicate_op65_write_state4 == 1'b1));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter8 = ((m_axi_gmem_BVALID == 1'b0) & (ap_predicate_op70_writeresp_state9 == 1'b1));
end

always @ (*) begin
    ap_condition_279 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_465 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_391_pp0_iter1_reg == 1'd0) & (icmp_ln27_reg_378_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_condition_469 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_391_pp0_iter1_reg == 1'd1) & (icmp_ln27_reg_378_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_condition_473 = ((icmp_ln43_fu_241_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln27_fu_219_p2 == 1'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_storemerge_reg_187 = 'bx;

assign ap_phi_reg_pp0_iter0_val_adc1_2_reg_197 = 'bx;

always @ (*) begin
    ap_predicate_op63_writereq_state3 = ((icmp_ln43_reg_391_pp0_iter1_reg == 1'd1) & (icmp_ln27_reg_378_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op65_write_state4 = ((icmp_ln43_reg_391_pp0_iter2_reg == 1'd1) & (icmp_ln27_reg_378_pp0_iter2_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op70_writeresp_state9 = ((icmp_ln43_reg_391_pp0_iter7_reg == 1'd1) & (icmp_ln27_reg_378_pp0_iter7_reg == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign empty_nbread_fu_132_p5_0 = adc_in_TVALID;

assign error_accum_flag_0_out = ap_phi_mux_error_accum_flag_0_phi_fu_178_p4;

assign error_accum_loc_0_out = error_accum_loc_0_fu_106;

assign icmp_ln27_fu_219_p2 = ((ap_sig_allocacmp_mem_idx_2 < max_samples) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_241_p2 = ((counter == 11'd1023) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARADDR = 64'd0;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd0;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_ARVALID = 1'b0;

assign m_axi_gmem_AWADDR = gmem_addr_reg_395_pp0_iter1_reg;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 64'd1;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_RREADY = 1'b0;

assign m_axi_gmem_WDATA = avg_error_reg_406;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 2'd3;

assign m_axi_gmem_WUSER = 1'd0;

assign mem_idx_3_fu_292_p2 = (ap_sig_allocacmp_mem_idx_2 + 32'd1);

assign sext_ln41_fu_328_p1 = $signed(ap_phi_reg_pp0_iter2_val_adc1_2_reg_197);

assign sext_ln47_fu_282_p1 = $signed(trunc_ln_fu_272_p4);

assign shl_ln_fu_254_p3 = {{ap_sig_allocacmp_mem_idx_2}, {1'd0}};

assign trunc_ln_fu_272_p4 = {{add_ln47_fu_266_p2[63:1]}};

assign val_adc1_fu_233_p1 = adc_in_TDATA[15:0];

assign zext_ln47_fu_262_p1 = shl_ln_fu_254_p3;

endmodule //PSDMonitorTop_PSDMonitorTop_Pipeline_VITIS_LOOP_27_1
