// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="PSDMonitorTop_PSDMonitorTop,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.840000,HLS_SYN_LAT=7,HLS_SYN_TPT=1,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=1209,HLS_SYN_LUT=1380,HLS_VERSION=2024_1}" *)

module PSDMonitorTop (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        adc_in_TDATA,
        adc_in_TVALID,
        adc_in_TREADY,
        adc_in_TKEEP,
        adc_in_TSTRB,
        adc_in_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input  [31:0] adc_in_TDATA;
input   adc_in_TVALID;
output   adc_in_TREADY;
input  [3:0] adc_in_TKEEP;
input  [3:0] adc_in_TSTRB;
input  [0:0] adc_in_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;

 reg    ap_rst_n_inv;
wire   [63:0] ram_buffer;
wire   [31:0] max_samples;
wire   [0:0] en_logging;
reg   [31:0] error_accum;
reg   [31:0] mem_idx;
reg   [10:0] counter;
reg    gmem_blk_n_AW;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] en_logging_read_reg_314;
reg   [0:0] icmp_ln35_reg_318;
reg   [0:0] icmp_ln38_reg_327;
reg    gmem_blk_n_W;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] en_logging_read_reg_314_pp0_iter1_reg;
reg   [0:0] icmp_ln35_reg_318_pp0_iter1_reg;
reg   [0:0] icmp_ln38_reg_327_pp0_iter1_reg;
reg    gmem_blk_n_B;
reg    ap_enable_reg_pp0_iter7;
reg   [0:0] en_logging_read_reg_314_pp0_iter6_reg;
reg   [0:0] icmp_ln35_reg_318_pp0_iter6_reg;
reg   [0:0] icmp_ln38_reg_327_pp0_iter6_reg;
reg    adc_in_TDATA_blk_n;
wire   [0:0] en_logging_read_read_fu_114_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
wire   [31:0] gmem_AWLEN;
reg    gmem_WVALID;
wire    gmem_WREADY;
wire    gmem_ARREADY;
wire    gmem_RVALID;
wire   [15:0] gmem_RDATA;
wire   [9:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg    ap_predicate_op62_writereq_state2;
reg    ap_block_state2_io;
reg    ap_predicate_op63_write_state3;
reg    ap_block_state3_io;
reg    ap_predicate_op68_writeresp_state8;
reg    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] en_logging_read_reg_314_pp0_iter2_reg;
reg   [0:0] en_logging_read_reg_314_pp0_iter3_reg;
reg   [0:0] en_logging_read_reg_314_pp0_iter4_reg;
reg   [0:0] en_logging_read_reg_314_pp0_iter5_reg;
wire   [0:0] icmp_ln35_fu_223_p2;
reg   [0:0] icmp_ln35_reg_318_pp0_iter2_reg;
reg   [0:0] icmp_ln35_reg_318_pp0_iter3_reg;
reg   [0:0] icmp_ln35_reg_318_pp0_iter4_reg;
reg   [0:0] icmp_ln35_reg_318_pp0_iter5_reg;
reg   [15:0] avg_error_reg_322;
reg   [15:0] avg_error_reg_322_pp0_iter1_reg;
wire   [0:0] icmp_ln38_fu_246_p2;
reg   [0:0] icmp_ln38_reg_327_pp0_iter2_reg;
reg   [0:0] icmp_ln38_reg_327_pp0_iter3_reg;
reg   [0:0] icmp_ln38_reg_327_pp0_iter4_reg;
reg   [0:0] icmp_ln38_reg_327_pp0_iter5_reg;
reg   [63:0] gmem_addr_reg_331;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg   [31:0] ap_phi_mux_error_accum_new_0_phi_fu_163_p6;
wire   [31:0] ap_phi_reg_pp0_iter0_error_accum_new_0_reg_160;
wire   [31:0] add_ln33_fu_212_p2;
reg   [10:0] ap_phi_mux_storemerge1_phi_fu_176_p6;
wire   [10:0] ap_phi_reg_pp0_iter0_storemerge1_reg_173;
wire   [10:0] add_ln46_fu_229_p2;
wire  signed [63:0] sext_ln39_fu_280_p1;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] add_ln40_fu_290_p2;
wire   [15:0] val_adc1_fu_190_p1;
wire  signed [31:0] sext_ln33_fu_208_p1;
wire   [32:0] shl_ln_fu_252_p3;
wire   [63:0] zext_ln39_fu_260_p1;
wire   [63:0] add_ln39_fu_264_p2;
wire   [62:0] trunc_ln_fu_270_p4;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_adc_in_V_data_V_U_apdone_blk;
wire   [31:0] adc_in_TDATA_int_regslice;
wire    adc_in_TVALID_int_regslice;
reg    adc_in_TREADY_int_regslice;
wire    regslice_both_adc_in_V_data_V_U_ack_in;
wire    regslice_both_adc_in_V_keep_V_U_apdone_blk;
wire   [3:0] adc_in_TKEEP_int_regslice;
wire    regslice_both_adc_in_V_keep_V_U_vld_out;
wire    regslice_both_adc_in_V_keep_V_U_ack_in;
wire    regslice_both_adc_in_V_strb_V_U_apdone_blk;
wire   [3:0] adc_in_TSTRB_int_regslice;
wire    regslice_both_adc_in_V_strb_V_U_vld_out;
wire    regslice_both_adc_in_V_strb_V_U_ack_in;
wire    regslice_both_adc_in_V_last_V_U_apdone_blk;
wire   [0:0] adc_in_TLAST_int_regslice;
wire    regslice_both_adc_in_V_last_V_U_vld_out;
wire    regslice_both_adc_in_V_last_V_U_ack_in;
reg    ap_condition_342;
reg    ap_condition_323;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 error_accum = 32'd0;
#0 mem_idx = 32'd0;
#0 counter = 11'd0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
end

PSDMonitorTop_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ram_buffer(ram_buffer),
    .max_samples(max_samples),
    .en_logging(en_logging)
);

PSDMonitorTop_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 10 ),
    .CH0_USER_DW( 16 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem_RDATA),
    .I_CH0_RFIFONUM(gmem_RFIFONUM),
    .I_CH0_AWVALID(gmem_AWVALID),
    .I_CH0_AWREADY(gmem_AWREADY),
    .I_CH0_AWADDR(gmem_addr_reg_331),
    .I_CH0_AWLEN(gmem_AWLEN),
    .I_CH0_WVALID(gmem_WVALID),
    .I_CH0_WREADY(gmem_WREADY),
    .I_CH0_WDATA(avg_error_reg_322_pp0_iter1_reg),
    .I_CH0_WSTRB(2'd3),
    .I_CH0_BVALID(gmem_BVALID),
    .I_CH0_BREADY(gmem_BREADY)
);

PSDMonitorTop_regslice_both #(
    .DataWidth( 32 ))
regslice_both_adc_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(adc_in_TDATA),
    .vld_in(adc_in_TVALID),
    .ack_in(regslice_both_adc_in_V_data_V_U_ack_in),
    .data_out(adc_in_TDATA_int_regslice),
    .vld_out(adc_in_TVALID_int_regslice),
    .ack_out(adc_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_adc_in_V_data_V_U_apdone_blk)
);

PSDMonitorTop_regslice_both #(
    .DataWidth( 4 ))
regslice_both_adc_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(adc_in_TKEEP),
    .vld_in(adc_in_TVALID),
    .ack_in(regslice_both_adc_in_V_keep_V_U_ack_in),
    .data_out(adc_in_TKEEP_int_regslice),
    .vld_out(regslice_both_adc_in_V_keep_V_U_vld_out),
    .ack_out(adc_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_adc_in_V_keep_V_U_apdone_blk)
);

PSDMonitorTop_regslice_both #(
    .DataWidth( 4 ))
regslice_both_adc_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(adc_in_TSTRB),
    .vld_in(adc_in_TVALID),
    .ack_in(regslice_both_adc_in_V_strb_V_U_ack_in),
    .data_out(adc_in_TSTRB_int_regslice),
    .vld_out(regslice_both_adc_in_V_strb_V_U_vld_out),
    .ack_out(adc_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_adc_in_V_strb_V_U_apdone_blk)
);

PSDMonitorTop_regslice_both #(
    .DataWidth( 1 ))
regslice_both_adc_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(adc_in_TLAST),
    .vld_in(adc_in_TVALID),
    .ack_in(regslice_both_adc_in_V_last_V_U_ack_in),
    .data_out(adc_in_TLAST_int_regslice),
    .vld_out(regslice_both_adc_in_V_last_V_U_vld_out),
    .ack_out(adc_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_adc_in_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_323)) begin
        if ((1'b1 == ap_condition_342)) begin
            mem_idx <= add_ln40_fu_290_p2;
        end else if ((en_logging_read_read_fu_114_p2 == 1'd0)) begin
            mem_idx <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        avg_error_reg_322 <= {{add_ln33_fu_212_p2[25:10]}};
        avg_error_reg_322_pp0_iter1_reg <= avg_error_reg_322;
        en_logging_read_reg_314 <= en_logging;
        en_logging_read_reg_314_pp0_iter1_reg <= en_logging_read_reg_314;
        gmem_addr_reg_331 <= sext_ln39_fu_280_p1;
        icmp_ln35_reg_318 <= icmp_ln35_fu_223_p2;
        icmp_ln35_reg_318_pp0_iter1_reg <= icmp_ln35_reg_318;
        icmp_ln38_reg_327 <= icmp_ln38_fu_246_p2;
        icmp_ln38_reg_327_pp0_iter1_reg <= icmp_ln38_reg_327;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == 1'b1))) begin
        counter <= ap_phi_mux_storemerge1_phi_fu_176_p6;
        error_accum <= ap_phi_mux_error_accum_new_0_phi_fu_163_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        en_logging_read_reg_314_pp0_iter2_reg <= en_logging_read_reg_314_pp0_iter1_reg;
        en_logging_read_reg_314_pp0_iter3_reg <= en_logging_read_reg_314_pp0_iter2_reg;
        en_logging_read_reg_314_pp0_iter4_reg <= en_logging_read_reg_314_pp0_iter3_reg;
        en_logging_read_reg_314_pp0_iter5_reg <= en_logging_read_reg_314_pp0_iter4_reg;
        en_logging_read_reg_314_pp0_iter6_reg <= en_logging_read_reg_314_pp0_iter5_reg;
        icmp_ln35_reg_318_pp0_iter2_reg <= icmp_ln35_reg_318_pp0_iter1_reg;
        icmp_ln35_reg_318_pp0_iter3_reg <= icmp_ln35_reg_318_pp0_iter2_reg;
        icmp_ln35_reg_318_pp0_iter4_reg <= icmp_ln35_reg_318_pp0_iter3_reg;
        icmp_ln35_reg_318_pp0_iter5_reg <= icmp_ln35_reg_318_pp0_iter4_reg;
        icmp_ln35_reg_318_pp0_iter6_reg <= icmp_ln35_reg_318_pp0_iter5_reg;
        icmp_ln38_reg_327_pp0_iter2_reg <= icmp_ln38_reg_327_pp0_iter1_reg;
        icmp_ln38_reg_327_pp0_iter3_reg <= icmp_ln38_reg_327_pp0_iter2_reg;
        icmp_ln38_reg_327_pp0_iter4_reg <= icmp_ln38_reg_327_pp0_iter3_reg;
        icmp_ln38_reg_327_pp0_iter5_reg <= icmp_ln38_reg_327_pp0_iter4_reg;
        icmp_ln38_reg_327_pp0_iter6_reg <= icmp_ln38_reg_327_pp0_iter5_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == 1'b1))) begin
        adc_in_TDATA_blk_n = adc_in_TVALID_int_regslice;
    end else begin
        adc_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == 1'b1))) begin
        adc_in_TREADY_int_regslice = 1'b1;
    end else begin
        adc_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b1 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln35_fu_223_p2 == 1'd0) & (en_logging_read_read_fu_114_p2 == 1'd1))) begin
        ap_phi_mux_error_accum_new_0_phi_fu_163_p6 = add_ln33_fu_212_p2;
    end else if (((en_logging_read_read_fu_114_p2 == 1'd0) | ((icmp_ln35_fu_223_p2 == 1'd1) & (en_logging_read_read_fu_114_p2 == 1'd1)))) begin
        ap_phi_mux_error_accum_new_0_phi_fu_163_p6 = 32'd0;
    end else begin
        ap_phi_mux_error_accum_new_0_phi_fu_163_p6 = ap_phi_reg_pp0_iter0_error_accum_new_0_reg_160;
    end
end

always @ (*) begin
    if (((icmp_ln35_fu_223_p2 == 1'd0) & (en_logging_read_read_fu_114_p2 == 1'd1))) begin
        ap_phi_mux_storemerge1_phi_fu_176_p6 = add_ln46_fu_229_p2;
    end else if (((en_logging_read_read_fu_114_p2 == 1'd0) | ((icmp_ln35_fu_223_p2 == 1'd1) & (en_logging_read_read_fu_114_p2 == 1'd1)))) begin
        ap_phi_mux_storemerge1_phi_fu_176_p6 = 11'd0;
    end else begin
        ap_phi_mux_storemerge1_phi_fu_176_p6 = ap_phi_reg_pp0_iter0_storemerge1_reg_173;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op62_writereq_state2 == 1'b1))) begin
        gmem_AWVALID = 1'b1;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op68_writeresp_state8 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        gmem_BREADY = 1'b1;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op63_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gmem_WVALID = 1'b1;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln38_reg_327 == 1'd1) & (icmp_ln35_reg_318 == 1'd1) & (en_logging_read_reg_314 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln38_reg_327_pp0_iter6_reg == 1'd1) & (icmp_ln35_reg_318_pp0_iter6_reg == 1'd1) & (en_logging_read_reg_314_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln38_reg_327_pp0_iter1_reg == 1'd1) & (icmp_ln35_reg_318_pp0_iter1_reg == 1'd1) & (en_logging_read_reg_314_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign adc_in_TREADY = regslice_both_adc_in_V_data_V_U_ack_in;

assign add_ln33_fu_212_p2 = ($signed(error_accum) + $signed(sext_ln33_fu_208_p1));

assign add_ln39_fu_264_p2 = (zext_ln39_fu_260_p1 + ram_buffer);

assign add_ln40_fu_290_p2 = (mem_idx + 32'd1);

assign add_ln46_fu_229_p2 = (counter + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'b1 == ap_block_state8_pp0_stage0_iter7) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((1'b1 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io)) | ((1'b1 == ap_block_state8_pp0_stage0_iter7) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((1'b1 == ap_block_state3_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io)) | ((1'b1 == ap_block_state8_pp0_stage0_iter7) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((1'b1 == ap_block_state3_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (1'b0 == adc_in_TVALID_int_regslice);
end

always @ (*) begin
    ap_block_state2_io = ((ap_predicate_op62_writereq_state2 == 1'b1) & (gmem_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op63_write_state3 == 1'b1) & (gmem_WREADY == 1'b0));
end

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7 = ((ap_predicate_op68_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0));
end

always @ (*) begin
    ap_condition_323 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == 1'b1));
end

always @ (*) begin
    ap_condition_342 = ((icmp_ln38_fu_246_p2 == 1'd1) & (icmp_ln35_fu_223_p2 == 1'd1) & (en_logging_read_read_fu_114_p2 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_error_accum_new_0_reg_160 = 'bx;

assign ap_phi_reg_pp0_iter0_storemerge1_reg_173 = 'bx;

always @ (*) begin
    ap_predicate_op62_writereq_state2 = ((icmp_ln38_reg_327 == 1'd1) & (icmp_ln35_reg_318 == 1'd1) & (en_logging_read_reg_314 == 1'd1));
end

always @ (*) begin
    ap_predicate_op63_write_state3 = ((icmp_ln38_reg_327_pp0_iter1_reg == 1'd1) & (icmp_ln35_reg_318_pp0_iter1_reg == 1'd1) & (en_logging_read_reg_314_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op68_writeresp_state8 = ((icmp_ln38_reg_327_pp0_iter6_reg == 1'd1) & (icmp_ln35_reg_318_pp0_iter6_reg == 1'd1) & (en_logging_read_reg_314_pp0_iter6_reg == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign en_logging_read_read_fu_114_p2 = en_logging;

assign gmem_AWLEN = 64'd1;

assign icmp_ln35_fu_223_p2 = ((counter == 11'd1023) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_246_p2 = ((mem_idx < max_samples) ? 1'b1 : 1'b0);

assign sext_ln33_fu_208_p1 = $signed(val_adc1_fu_190_p1);

assign sext_ln39_fu_280_p1 = $signed(trunc_ln_fu_270_p4);

assign shl_ln_fu_252_p3 = {{mem_idx}, {1'd0}};

assign trunc_ln_fu_270_p4 = {{add_ln39_fu_264_p2[63:1]}};

assign val_adc1_fu_190_p1 = adc_in_TDATA_int_regslice[15:0];

assign zext_ln39_fu_260_p1 = shl_ln_fu_252_p3;

endmodule //PSDMonitorTop
